config/routes.rb
Rails.application.routes.draw do
  default_url_options host: "localhost:3005"

  root to: redirect("/orders")

  # Обработка запросов из кабинета
  namespace :web, path: "" do
    resources :orders, only: %i[index show]
    resources :pays, only: %i[show create] do
      member do
        get "success"
        get "failure"
      end
    end

    # Страницы ошибок
    get "not_found", to: "errors#not_found", as: :not_found
    get "unknown_error", to: "errors#unknown_error", as: :unknown_error
  end

  # Обработка запросов от внешних систем
  namespace :api do
    get "pay/success", to: "pay_callback#successful"
    get "pay/failed", to: "pay_callback#failed"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/order_statuses.rb
# frozen_string_literal: true

##
# Статусы заказа
#
module OrderStatuses
  extend ActiveSupport::Concern

  included do
    ##
    # Данные для представления статусов
    #
    # @return [Hash<Symbol>]
    #
    def self.hash_statuses
      { init: 0, start: 1, error: 2, finish: 3 }
    end

    ##
    # Список доступных статусов
    #
    # @return [Array<String>]
    #
    def self.avaliable_statuses
      hash_statuses.keys.map(&:to_s)
    end
  end
end

app/models/order.rb
# frozen_string_literal: true

##
# Сущность заказа
#
class Order < ApplicationRecord
  include OrderStatuses
  has_many :order_line, dependent: :destroy
  validates :user_name, :phone, :email, :address, :total, presence: true
  # новый, начата оплата, ошибка оплаты, оплачен
  enum :status, hash_statuses

  scope :started_pay, -> { where(status: :start) }

  def human_status
    I18n.t("models.data.order.#{status}")
  end
end

app/models/order_line.rb
# frozen_string_literal: true

##
# Сущность строк заказа
# хранит информацию о товаре
#
class OrderLine < ApplicationRecord
  belongs_to :order, optional: true
  validates :name, :cost, :count, :total, presence: true
  validate :total_sum_check

  private
    def total_sum_check
      return if cost.present? && count.present? && total.eql?(cost * count)

      errors.add(:total, I18n.t("errors.order_line.total"))
    end
end

app/controllers/api/api_controller.rb
# frozen_string_literal: true

module Api
  ##
  # Контроллер для взаимодействия с внешними сервисами
  #
  class ApiController < ActionController::API
    rescue_from Exception, with: :unknown_error_callback
    rescue_from ActiveRecord::RecordNotFound, with: :not_found_callbac
    before_action :ensure_json_request

    private
      def ensure_json_request
        return if Rails.env.development?
        return if request.format == :json
        return if request.headers["Content-Type"] == "application/json"

        head :not_acceptable and return
      end

      def not_found_callbac
        head :not_found
      end

      def unknown_error_callback(err)
        DevelopmentMailer.unknown_error(err)
        head :internal_server_error
      end
  end
end

app/controllers/api/pay_callback_controller.rb
# frozen_string_literal: true

module Api
  ##
  # Перехват колбеков от оплаты заказа
  #
  class PayCallbackController < ApiController
    before_action :find_order

    SBER_CALLBACK_ACTION = %i[successful failed].freeze

    SBER_CALLBACK_ACTION.each do |type_callback|
      ##
      # Перехват коллбеков оплаты от сбербанка
      # успешная или не успешная оплата
      #
      define_method type_callback do
        @type_callback = type_callback
        if callback_service.call.success?
          redirect_to success_redirect_page
        else
          redirect_to web_unknown_error_path
        end
      end
    end

    private
      def callback_params
        params.permit(:mdOrder, :orderNumber, :operation, :callbackCreationDate, :status)
      end

      ##
      # Поиск заказа по orderNumber, который сохранили при отправке на оплату
      #
      # @return [Order]
      #
      def find_order
        @order = ::Order.started_pay.find(callback_params[:orderNumber])
      end

      def callback_service
        @callback_service ||= ::Api::Pays::SberOrderCallbackOperation.new(
          order: @order, type: @type_callback, params: callback_params
        )
      end

      ##
      # URL страница после оплаты
      #
      # @return [String]
      #
      def success_redirect_page
        if callback_service.finish_pay?
          success_web_pay_path(@order.id)
        else
          failure_web_pay_path(@order.id)
        end
      end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/web/errors_controller.rb
# frozen_string_literal: true

module Web
  ##
  # Выдача страниц с ошибками
  #
  class ErrorsController < WebController
    ##
    # Страница 404
    #
    def not_found; end

    ##
    # Ошибка на стороне сервера
    #
    def unknown_error; end
  end
end

app/controllers/web/orders_controller.rb
# frozen_string_literal: true

module Web
  ##
  # Действия с заказами
  #
  class OrdersController < WebController
    # before_action :authenticate_user!

    ##
    # Страница со списоком задач
    #
    def index
      @orders = ::Order.all.order(created_at: :desc)
    end

    ##
    # Просмотр странички заказа
    #
    def show
      @order = ::Order.preload(:order_line).find(order_param[:id])
    end

    private
      def order_param
        params.permit(:id)
      end
  end
end

app/controllers/web/pays_controller.rb
# frozen_string_literal: true

module Web
  ##
  # Контроллер оплаты заказа
  #
  class PaysController < WebController
    before_action :find_order
    CALLBACK_ACTIONS = %i[success failure].freeze

    ##
    # ТЕСТОВАЯ страница для мока страницы от сбера
    # Выбор сценария колбека положительного или отрицательного
    #
    def show
      @params_for_redirect = stub_test_callback_sber_params
      @success_url = ::Api::Pays::Sber.success_url(order_id: @order.id)
      @failure_url = ::Api::Pays::Sber.fail_url(order_id: @order.id)
    end

    ##
    # Оплата заказа
    #
    def create
      result = ::Web::Pays::PayThroughSberOperation.new(order: @order).call
      if result.success?
        redirect_to result.value![:redirect_url], allow_other_host: true
      else
        redirect_to web_unknown_error_path
      end
    end

    CALLBACK_ACTIONS.each do |method_name|
      ##
      # Страницы после успешной или провальной оплаты заказа
      #
      define_method method_name do
        flash_message(method_name == :success)
        render "web/orders/show"
      end
    end

    private
      def create_params
        params.permit(:id)
      end

      ##
      # Поиск заказа по ID из параметров
      #
      # @return [Order]
      #
      def find_order
        @order = ::Order.find(create_params[:id])
      end

      def flash_message(finish_pay)
        if finish_pay
          flash.now[:notice] = text_for_alert(finish_pay)
        else
          flash.now[:alert] = text_for_alert(finish_pay)
        end
      end

      def text_for_alert(finish_pay)
        finish_pay ? I18n.t("success.pay.finish") : I18n.t("errors.pay.error")
      end

      ##
      # Стаб параметров в коллбеке от сбера
      #
      def stub_test_callback_sber_params
        {
          success: {
            mdOrder: 132,
            orderNumber: @order.id,
            operation: "deposited",
            callbackCreationDate: Time.current,
            status: 1
          },
          failure: {
            mdOrder: 132,
            orderNumber: @order.id,
            operation: "deposited",
            callbackCreationDate: Time.current,
            status: 0
          }
        }
      end
  end
end

app/controllers/web/web_controller.rb
# frozen_string_literal: true

module Web
  ##
  # Для запросов из кабинета.
  #
  class WebController < ApplicationController
    rescue_from Exception, with: :unknown_error
    rescue_from ActiveRecord::RecordNotFound, with: :not_found
    before_action :set_cors_headers
    layout "web"

    def set_cors_headers
      response.headers["Access-Control-Allow-Headers"] = "Content-Type, Accept, Authorization"
      response.headers["Access-Control-Allow-Methods"] = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
      response.headers["Access-Control-Allow-Origin"] = request.origin
      response.headers["Access-Control-Request-Method"] = "*"
    end

    def unknown_error(err)
      DevelopmentMailer.unknown_error(err)
      redirect_to web_unknown_error_path
    end

    def not_found
      redirect_to web_not_found_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiteBlogRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "main" %>
    <%= javascript_importmap_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar" %>
    </header>
    <main>
      <div class="container">
        <% flash.each do |type, msg| %>
          <% if type == "notice" %>
            <div class="notice"><%= msg %></div>
          <% else %>
            <div class="alert"><%= msg %></div>
          <% end %>
        <% end %>

        <%= yield %>
      </div>
    </main>
  </body>
  <script>
    $('document').ready(function() {
      setTimeout(function() {
        $('.notice').slideUp();
      }, 3000);
    });
  </script>
</html>

app/views/layouts/web.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartomatoTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <header>
      <%= render partial: "partials/web/header" %>
    </header>
    <main>
      <div class="container mx-auto">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/partials/web/_flash.html.erb
<% if flash[:alert].present? %>
  <div style="color: red;" >
    <%= flash[:alert] %>
  </div>
<% end %>
<% if flash[:notice].present? %>
  <div style="color: green;" >
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/partials/web/_header.html.erb
<nav
  class="relative flex w-full flex-wrap items-center justify-between bg-[#FBFBFB] py-2 text-neutral-500 shadow-lg hover:text-neutral-700 focus:text-neutral-700 dark:bg-neutral-600 lg:py-4"
  data-te-navbar-ref>
  <div class="flex w-full flex-wrap items-center justify-between px-3">
    <div>
      <a
        class="mx-2 my-1 flex items-center text-neutral-900 hover:text-neutral-900 focus:text-neutral-900 lg:mb-0 lg:mt-0"
        href="#">
        <img
          class="mr-2"
          src="https://smartomato.ru/new-landing/assets/svg-logo-1989ec51e667cb055ee420a363c203d7bc9a3c0ef554ebc1e96d2ae48f6f842c.svg"
          style="height: 35px"
          alt="TE Logo"
          loading="lazy" />
      </a>
    </div>

    <button
      class="block border-0 bg-transparent px-2 text-neutral-500 hover:no-underline hover:shadow-none focus:no-underline focus:shadow-none focus:outline-none focus:ring-0 dark:text-neutral-200 lg:hidden"
      type="button"
      data-te-collapse-init
      data-te-target="#navbarSupportedContent4"
      aria-controls="navbarSupportedContent4"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="[&>svg]:w-7">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="currentColor"
          class="h-7 w-7">
          <path
            fill-rule="evenodd"
            d="M3 6.75A.75.75 0 013.75 6h16.5a.75.75 0 010 1.5H3.75A.75.75 0 013 6.75zM3 12a.75.75 0 01.75-.75h16.5a.75.75 0 010 1.5H3.75A.75.75 0 013 12zm0 5.25a.75.75 0 01.75-.75h16.5a.75.75 0 010 1.5H3.75a.75.75 0 01-.75-.75z"
            clip-rule="evenodd" />
        </svg>
      </span>
    </button>

    <div
      class="!visible mt-2 hidden flex-grow basis-[100%] items-center lg:mt-0 lg:!flex lg:basis-auto"
      id="navbarSupportedContent4"
      data-te-collapse-item>
      <ul
        class="list-style-none mr-auto flex flex-col pl-0 lg:mt-1 lg:flex-row"
        data-te-navbar-nav-ref>
        <li
          class="my-4 pl-2 lg:my-0 lg:pl-2 lg:pr-1"
          data-te-nav-item-ref>
          <%= link_to "Заказы", web_orders_path, aria_current: "page", class: "text-neutral-500 hover:text-neutral-700 focus:text-neutral-700 disabled:text-black/30 dark:text-neutral-200 dark:hover:text-neutral-400 dark:focus:text-neutral-400 lg:px-2 [&.active]:text-black/90 dark:[&.active]:text-neutral-400" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/web/orders/_order.html.erb
<%= link_to web_order_url(order.id) do %>
    <div class="w-1/2 p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= "ID: #{order.id}. Заказ клиента: #{order.user_name}." %></h5>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= content_tag(:span, "Статус заказа: #{order.human_status}.", style: "color: green;") %> <%= "Дата создания: #{order.created_at}" %></p>
    </div>
<% end %>

app/views/web/orders/_order_line.html.erb
<hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700">

<dl class="max-w-md text-gray-900 divide-y divide-gray-200 dark:text-white dark:divide-gray-700">
    <div class="flex flex-col pb-3">
        <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Название товара</dt>
        <dd class="text-lg font-semibold"><%= order_line.name %></dd>
    </div>
    <div class="flex flex-col py-3">
        <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Стоимость товара</dt>
        <dd class="text-lg font-semibold"><%= order_line.cost.to_f %></dd>
    </div>
    <div class="flex flex-col pt-3">
        <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Количество товаров</dt>
        <dd class="text-lg font-semibold"><%= order_line.count %></dd>
    </div>
    <div class="flex flex-col pt-3">
        <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Общая стоимость товаров</dt>
        <dd class="text-lg font-semibold"><%= order_line.total %></dd>
    </div>
</dl>

app/views/web/orders/index.html.erb
<div>
  <h2 class="text-4xl font-bold tracking-tight text-gray-900">Заказы</h2>
  <%= render partial: "order", collection: @orders %>
</div>

app/views/web/orders/show.html.erb
<% if flash.present? %>
    <%= render partial: "partials/web/flash" %>
<% end %>
<h1 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= "ID: #{@order.id}. Заказ клиента: #{@order.user_name}." %></h1>
<div>
    <div style="vertical-align: middle;">
        <dl class="max-w-md text-gray-900 divide-y divide-gray-200 dark:text-white dark:divide-gray-700">
            <div class="flex flex-col pb-3">
                <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Имя пользователя</dt>
                <dd class="text-lg font-semibold"><%= @order.user_name %></dd>
            </div>
            <div class="flex flex-col py-3">
                <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Номер телефона</dt>
                <dd class="text-lg font-semibold"><%= @order.phone %></dd>
            </div>
            <div class="flex flex-col pt-3">
                <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Почта</dt>
                <dd class="text-lg font-semibold"><%= @order.email %></dd>
            </div>
            <div class="flex flex-col pt-3">
                <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Адрес</dt>
                <dd class="text-lg font-semibold"><%= @order.address %></dd>
            </div>
            <div class="flex flex-col pt-3">
                <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Статус заказа</dt>
                <dd class="text-lg font-semibold"><%= @order.human_status %></dd>
            </div>
        </dl>
    </div>
    <div class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" stype="vertical-align: middle;">
        <%= button_to "Оплатить", web_pays_path, params: { id: @order.id } %>
    </div>
</div>
<div class="grid place-items-center h-screen">
    <h2 class="mb-2 text-lg font-semibold text-gray-900 dark:text-white">Список товаров:</h2>
    <%= render partial: "web/orders/order_line", collection: @order.order_line %>
</div>

app/views/web/pays/show.html.erb
<h1 class="text-4xl font-bold tracking-tight text-gray-900" style="margin-bottom: 20px;">Мокнутая страница сбера</h1>

<%= button_to "Положительный коллбек", @success_url, method: :get, params: @params_for_redirect[:success], class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded", style: "display: flex;" %>
<%= button_to "Отрицательный коллбек", @failure_url, method: :get, params: @params_for_redirect[:failure], class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded", style: "display: flex;" %>
<%= link_to "Просто назад к странице заказа", web_order_path(@order.id), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>